version: '3.8'
services:
  gql-api:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=pg
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
